[0m12:56:54.496643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102116910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103e18190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10492ffd0>]}


============================== 12:56:54.500400 | c89a2dc6-7bef-421c-9934-47dfc70169d4 ==============================
[0m12:56:54.500400 [info ] [MainThread]: Running with dbt=1.9.6
[0m12:56:54.500845 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/yash/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init claims_etl_dbt', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:56:54.509791 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/yash/.dbt')}
[0m12:56:54.510102 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:56:54.511142 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:56:54.515473 [info ] [MainThread]: 
Your new dbt project "claims_etl_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:56:54.515728 [info ] [MainThread]: Setting up your profile.
[0m13:07:20.148379 [info ] [MainThread]: Profile claims_etl_dbt written to /Users/yash/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:07:20.176881 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 514.7301, "process_in_blocks": "0", "process_kernel_time": 0.197511, "process_mem_max_rss": "101908480", "process_out_blocks": "0", "process_user_time": 0.943442}
[0m13:07:20.177835 [debug] [MainThread]: Command `dbt init` succeeded at 13:07:20.177646 after 514.74 seconds
[0m13:07:20.178928 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048d5f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048d4590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1003391d0>]}
[0m13:07:20.179981 [debug] [MainThread]: Flushing usage events
[0m13:07:20.696555 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:08:13.384866 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10639a9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bbfed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bbffd0>]}


============================== 13:08:13.388598 | c7b3f71a-4f7a-446c-9d7a-528fe69a2415 ==============================
[0m13:08:13.388598 [info ] [MainThread]: Running with dbt=1.9.6
[0m13:08:13.389044 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yash/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:08:13.398758 [info ] [MainThread]: dbt version: 1.9.6
[0m13:08:13.399019 [info ] [MainThread]: python version: 3.11.4
[0m13:08:13.399236 [info ] [MainThread]: python path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
[0m13:08:13.399425 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit
[0m13:08:13.454089 [info ] [MainThread]: Using profiles dir at /Users/yash/.dbt
[0m13:08:13.454408 [info ] [MainThread]: Using profiles.yml file at /Users/yash/.dbt/profiles.yml
[0m13:08:13.454605 [info ] [MainThread]: Using dbt_project.yml file at /Users/yash/healthcare-claims-etl/dbt_project.yml
[0m13:08:13.454942 [info ] [MainThread]: adapter type: postgres
[0m13:08:13.455118 [info ] [MainThread]: adapter version: 1.9.0
[0m13:08:13.455285 [info ] [MainThread]: Configuration:
[0m13:08:13.455444 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:08:13.455596 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:08:13.455745 [info ] [MainThread]: Required dependencies:
[0m13:08:13.455928 [debug] [MainThread]: Executing "git --help"
[0m13:08:13.474636 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:08:13.475220 [debug] [MainThread]: STDERR: "b''"
[0m13:08:13.475427 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:08:13.475629 [info ] [MainThread]: Connection:
[0m13:08:13.475832 [info ] [MainThread]:   host: claims_etl_dbt
[0m13:08:13.475992 [info ] [MainThread]:   port: 5432
[0m13:08:13.477403 [info ] [MainThread]:   user: claims_db
[0m13:08:13.477575 [info ] [MainThread]:   database: claims_db
[0m13:08:13.477727 [info ] [MainThread]:   schema: public
[0m13:08:13.477877 [info ] [MainThread]:   connect_timeout: 10
[0m13:08:13.478025 [info ] [MainThread]:   role: None
[0m13:08:13.478180 [info ] [MainThread]:   search_path: None
[0m13:08:13.478325 [info ] [MainThread]:   keepalives_idle: 0
[0m13:08:13.478473 [info ] [MainThread]:   sslmode: None
[0m13:08:13.478618 [info ] [MainThread]:   sslcert: None
[0m13:08:13.478765 [info ] [MainThread]:   sslkey: None
[0m13:08:13.478910 [info ] [MainThread]:   sslrootcert: None
[0m13:08:13.479060 [info ] [MainThread]:   application_name: dbt
[0m13:08:13.479208 [info ] [MainThread]:   retries: 1
[0m13:08:13.479528 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m13:08:13.554357 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m13:08:13.597371 [debug] [MainThread]: Using postgres connection "debug"
[0m13:08:13.597640 [debug] [MainThread]: On debug: select 1 as id
[0m13:08:13.597830 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:08:13.668244 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "claims_etl_dbt" to address: nodename nor servname provided, or not known

[0m13:08:13.670807 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m13:08:13.671002 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m13:08:13.671198 [debug] [MainThread]: On debug: No close available on handle
[0m13:08:13.671400 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m13:08:13.671653 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:08:13.671827 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/yash/healthcare-claims-etl/dbt_project.yml> not found

[0m13:08:13.672002 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  could not translate host name "claims_etl_dbt" to address: nodename nor servname provided, or not known
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m13:08:13.674186 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.34062004, "process_in_blocks": "0", "process_kernel_time": 0.224137, "process_mem_max_rss": "109576192", "process_out_blocks": "0", "process_user_time": 1.002867}
[0m13:08:13.674546 [debug] [MainThread]: Command `dbt debug` failed at 13:08:13.674465 after 0.34 seconds
[0m13:08:13.674782 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:08:13.675013 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ba5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b62050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10911a390>]}
[0m13:08:13.675283 [debug] [MainThread]: Flushing usage events
[0m13:08:13.955871 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:20:26.358715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10734a8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107378490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107378bd0>]}


============================== 13:20:26.362703 | ee66bedd-b7d4-437e-aae4-19ce2a1bc358 ==============================
[0m13:20:26.362703 [info ] [MainThread]: Running with dbt=1.9.6
[0m13:20:26.363177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yash/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init claims_etl_dbt', 'send_anonymous_usage_stats': 'True'}
[0m13:20:26.373678 [info ] [MainThread]: A project called claims_etl_dbt already exists here.
[0m13:20:26.375805 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.06866112, "process_in_blocks": "0", "process_kernel_time": 0.168747, "process_mem_max_rss": "102105088", "process_out_blocks": "0", "process_user_time": 0.912076}
[0m13:20:26.376153 [debug] [MainThread]: Command `dbt init` succeeded at 13:20:26.376075 after 0.07 seconds
[0m13:20:26.376443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102c8cfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073060d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102d6c710>]}
[0m13:20:26.376719 [debug] [MainThread]: Flushing usage events
[0m13:20:26.917941 [debug] [MainThread]: An error was encountered while trying to flush usage events
